// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPHQxvkdbhgIVtAmc9D-h6tWQfAAUO1f0',
    appId: '1:337102564440:web:ebc0e1b9feb251fda9ae2d',
    messagingSenderId: '337102564440',
    projectId: 'first-app-bc00d',
    authDomain: 'first-app-bc00d.firebaseapp.com',
    storageBucket: 'first-app-bc00d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzbcN5jQ58L9pk9wFQGVUgqz4BXMzgMvA',
    appId: '1:337102564440:android:9437dbe9be3f06e8a9ae2d',
    messagingSenderId: '337102564440',
    projectId: 'first-app-bc00d',
    storageBucket: 'first-app-bc00d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfPOvQZ_7_hTZzrHZD31gUzUvqMuCIaQ',
    appId: '1:337102564440:ios:674a61cd88e9a38aa9ae2d',
    messagingSenderId: '337102564440',
    projectId: 'first-app-bc00d',
    storageBucket: 'first-app-bc00d.appspot.com',
    iosClientId: '337102564440-2khranpc43ostmrl7m7h2cof3b9pba0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfPOvQZ_7_hTZzrHZD31gUzUvqMuCIaQ',
    appId: '1:337102564440:ios:bb8d9b775dadc305a9ae2d',
    messagingSenderId: '337102564440',
    projectId: 'first-app-bc00d',
    storageBucket: 'first-app-bc00d.appspot.com',
    iosClientId: '337102564440-dts9q135facno2qlnsiuiveis3e5bgjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulus.RunnerTests',
  );
}
